### PR TITLE
Logo Created

### PR DESCRIPTION
**Pull request by Manoj13-coder**

### CODE REVIEW

**Comment by peterjc** [comment]
[OBF text with the current round lock and DNA logo inside the O; green]

Did you have a specific usage in mind?

**Comment by Manoj13-coder** [comment]
so you don't like it ?

**Comment by peterjc** [comment]
I meant was is intended for #82, or #83, or did you have something else in mind?

**Comment by Manoj13-coder** [comment]
no

**Comment by Manoj13-coder** [comment]
can i try it one more time ?

**Comment by Manoj13-coder** [comment]
just tell me little bit about your opinion what type of changes do you want .
and i have a doubt do i have to make logo based on old logos or can i make new one.

**Comment by Manoj13-coder** [comment]
i will try my best this time

**Comment by peterjc** [comment]
Why are you designing a new logo? Our first logo was designed about 20 years ago. Our second and current logo is only about 2 years old, I don't think it needs changing.

Personally I find your design to busy for use as a logo, and too bold for use as a twitter banner (#82). Perhaps better suited to #81, but it is a bit different to the current OBF styling. The rest of the board may have different views - logos and graphics are very subjective.

**Comment by yochannah** [comment]
@Manoj13-coder thanks for the effort you've put into this, I'm guessing it took you some time :) as Peter mentioned, we're not specifically looking for a logo at the minute.

Since we're not looking for a logo and this doesn't match the size specs for #81 and #82, I'm going to close this PR for now, but leave you assigned to #81 and #82. 

I do think this work could be adjusted to be suitable for #81 and #82, but here are a few tips: 

1. Make sure to read the specs for each of the tasks carefully - we're asking for SVG files (as well as a jpg or png), and we'd like to exactly match the OBF green/white colouring that we already have - that one shade of green is probably enough for now :) - in addition, each of those two tasks has a very specific set of pixel dimensions needed. Do you have some SVG editing software? 
2. If you'd like to give this another go (you'd be very welcome to!), maybe try making a white background with obf-green text or an obf-green background with white text, and try to match the same fonts as the logo currently has. Keep things simple - I don't think we need a drop shadow, and possibly good text would be "Open Bioinformatics Foundation" rather than just OBF. See this file here: https://github.com/OBF/obf-docs/blob/master/logos/green_color.txt for the hex-colour of the green. 

Hopefully you're happy to give this another go, but if you prefer to be unassigned please let me know so we can free the tasks up for another contributor :)

**Comment by Manoj13-coder** [comment]
ok understood

**Pull request closed without merging**
