### PR TITLE
Shift to two rounds per year; no past events

### PR DESCRIPTION
**Pull request by peterjc**
Changes discussed by the OBF board on 10 September 2019.

### CODE REVIEW

**Comment by peterjc** [comment]
Anyone on the board want to second this approval?

**Comment by peterjc** [comment]
I make that four approvals:

* Me (as author)
* Hilmar (via comment)
* Nomi (via thumbs up)
* Bastian (via Github approval)

(As discussed by email, we should standardise on a single mechanism here)

With eight on the board, one more and we can merge this with majority approval...

**Comment by hlapp** [comment]
Just FYI, I also approved the PR 😊 (and now that there's more than one, it appears that Github does count those too)

**Comment by HLWiencko** [comment]
Yep, I approve.

<> )-( <>

**Comment by peterjc** [comment]
Merged, thanks all.

Next, we need to update the website...

**Comment by peterjc** [comment]
The changes up on https://www.open-bio.org/travel-awards/ looks good to me.

**Pull request merged**
