### PR TITLE
cover child-care + non-flight travel costs in Travel Fellowship

### PR DESCRIPTION
**Pull request by peterjc**
See discussion started on email - child-care can be a substantial cost which the original wording excluded. Likewise, the airfare may not be the only or main travel costs (e.g. train).

Note: Should we explicitly exclude personal car mileage (problematic with setting a rate or documenting with receipts)?

### CODE REVIEW

**Comment by hlapp** [comment]
> Should we explicitly exclude personal car mileage (problematic with setting a rate or documenting with receipts)?

Yes, I think we should. Mileage rates are local, differ widely, and also can differ considerably in required documentation.

We should also exclude rental car expenses.

**Comment by yochannah** [comment]
I imagine that anywhere someone may be arranging a conference will have public transport, arranged shuttles, or taxis at the least, so it seems reasonable.

**Comment by peterjc** [comment]
How about:

"The fellowship can be used to cover direct travel costs (airfare, train, metro, bus and taxi, but not rental cars or mileage), hotel, child-care and / or conference registration fees up to a value of USD 1,000."

**Comment by hlapp** [comment]
I would suggest to word it such that the list can't be read as comprehensive. For example:

> The fellowship can be used to cover direct travel costs (such as airfare, train, metro, bus and taxi), hotel, child-care and / or conference registration fees up to a value of USD 1,000. Note that rental car expenses and personal car mileage are not eligible for reimbursement.

**Comment by nlharris** [comment]
Yes, I like @hlapp's wording better.

**Comment by peterjc** [comment]
Updated with Hilmar's wording - we can discuss merging this at our next hangout.

**Comment by peterjc** [comment]
Agreed by the board.

**Pull request merged**
